image: Visual Studio 2022

version: "{build}-{branch}"

branches:
  only:
    - main
    - dev/appveyor

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 27-x64
    - RUBY_VERSION: 31-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  # - bundle env
  - gem update --no-document --system
  - gem install bundler --no-document --version="<3.0.0"
  - bundle config set --local path vendor/bundle
  - bundle config set --local without analysis development documentation
  - bundle config set --local with test
  # - bundle env
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test
